name: Deploy Streamlit App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r agentsetup/requirements.txt
        
    - name: Run basic tests
      run: |
        # Test that all modules can be imported
        cd agentsetup
        python -c "import streamlit; print('Streamlit import successful')"
        python -c "import fastapi; print('FastAPI import successful')"
        python -c "import main; print('Main module import successful')"
        
    - name: Test Streamlit app syntax
      run: |
        cd agentsetup
        python -m py_compile streamlit_app.py
        echo "Streamlit app syntax check passed"

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r agentsetup/requirements.txt
        
    - name: Create deployment package
      run: |
        # Create a zip file with the application
        cd agentsetup
        zip -r ../deployment.zip . -x "__pycache__/*" "*.pyc"
        cd ..
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './deployment.zip'